# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_stack <- function(array_list, along, fill, ovr) {
    .Call('_narray_cpp_stack', PACKAGE = 'narray', array_list, along, fill, ovr)
}

